### ISSUE TITLE
no joining on server

### ISSUE THREAD

**Issue by alexsprokosin** [XidMods05/brawl-stars-v36-private-server#4]
im setting ip addres and no joining on game((

**Comment by alexsprokosin** [comment]
oh im fixed problem on get new problem.... [WARN] Unknown message received! Information: type: 10100; name: ClientHelloMessage.

**Comment by alexsprokosin** [comment]
![VeloBrawl (Отладка) - Microsoft Visual Studio 16 09 2024 20_24_49](https://github.com/user-attachments/assets/908edd2c-8cfb-4867-8292-b8a8b5a73e89)

**Comment by XidMods05** [comment]
> oh im fixed problem on get new problem.... [WARN] Unknown message received! Information: type: 10100; name: ClientHelloMessage.

Hi, try using this script (https://github.com/superdudnikteam/brawl-stars-shit-scripts/blob/main/v36.218.js )

Привет, попробуй использовать этот скрипт (https://github.com/superdudnikteam/brawl-stars-shit-scripts/blob/main/v36.218.js)

**Comment by XidMods05** [comment]
> ![VeloBrawl (Отладка) - Microsoft Visual Studio 16 09 2024 20_24_49](https://private-user-images.githubusercontent.com/143007502/367719668-908edd2c-8cfb-4867-8292-b8a8b5a73e89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTExNDksIm5iZiI6MTcyNjUxMDg0OSwicGF0aCI6Ii8xNDMwMDc1MDIvMzY3NzE5NjY4LTkwOGVkZDJjLThjZmItNDg2Ny04MjkyLWI4YThiNWE3M2U4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxODIwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Yjk4NTE5YjllODExZmI4NjUzMDg4ZmQ4YTRmNzNhZDMxNTk2ODJiNzNjOWQxZjQxZDMyNzNlMmMxYzIyYjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aDxpjYTaGnEdylb6gn7atysSpqMwRXX25awlJCMdPRM)

Try to restart it.
Попробуй перезапустить.

**Comment by alexsprokosin** [comment]
![Screenshot_2024-09-18-14-46-24-777_com cb brawlstars v36](https://github.com/user-attachments/assets/0811e2fa-3727-449d-9d68-0421c4c86940)
Вот теперь всё заработало, но бывает то что клиент вылетает.

**Comment by XidMods05** [comment]
> ![Screenshot_2024-09-18-14-46-24-777_com cb brawlstars v36](https://private-user-images.githubusercontent.com/143007502/368424758-0811e2fa-3727-449d-9d68-0421c4c86940.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMjE2MzQsIm5iZiI6MTcyNzAyMTMzNCwicGF0aCI6Ii8xNDMwMDc1MDIvMzY4NDI0NzU4LTA4MTFlMmZhLTM3MjctNDQ5ZC05ZDY4LTA0MjFjNGM4Njk0MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNjA4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmUzN2JhYTJkYmQzMGIyNDc5ZGFjZmJiNWRlMjA2MTA5NjkzNmRkZmZmNjA5ODYzMmFmMjk0NzkyNjEyMjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fYr5bro3LLnoICZYY9zZgbMlWCEs07qlTeheA5B33xs) Вот теперь всё заработало, но бывает то что клиент вылетает.

У тебя активировался оффлайн бой. 

Чтоб активировать онлайн удали строки Interceptor.attach(base.add(0x511000), {
		onEnter(args) {
			args[3] = ptr(3);
		}
	}); со скрипта (начинаются на 59 строке) 

А еще ты должен указать свой IP адрес в VeloBrawl/Program.cs (например 192.168.0.11)
